name: build

on: 
  push:
    paths: 
      - NativeLibs/yasio/**
      - .github/workflows/build.yml

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK=$(pwd)/android-ndk-r19c
      - name: Build
        run: |
          cd NativeLibs/yasio
          sudo apt-get update --fix-missing
          sudo apt install gcc-multilib
          ./build_android.sh
          ./build_android_arm64.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./NativeLibs/yasio/plugin_android/**/*
          name: plugin_android
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd NativeLibs/yasio
          ./build_linux.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./NativeLibs/yasio/plugin_linux/**/*
          name: plugin_linux
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd NativeLibs/yasio
          ./build_ios.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./NativeLibs/yasio/plugin_ios/**/*
          name: plugin_ios
      
  osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd NativeLibs/yasio
          ./build_osx.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./NativeLibs/yasio/plugin_osx/**/*
          name: plugin_osx
      
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Build
        run: |
          cd NativeLibs/yasio
          .\build_win.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./NativeLibs/yasio/plugin_win/**/*
          name: plugin_win
          
  download-test:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
      - name: Display structure of downloaded files
        run: ls -R
